global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'emqx'
    static_configs:
      - targets: ['emqx:18083']
    metrics_path: /api/v5/prometheus/stats
    basic_auth:
      username: admin
      password: public

  - job_name: 'loadgen'
    static_configs:
      - targets: ['loadgen-v2:8090']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker-v2:8080']
